# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cG1fNMXCgYUybhV4WguADhtuEQj7nlI5
"""

pip install streamlit

import pandas as pd
import streamlit as st

st.title("スプレッドシート解析アプリ")
st.write("CSVまたはExcelファイルをアップロードしてください。")

# ファイルアップロード
uploaded_file = st.file_uploader("ファイルを選択", type=["csv", "xls", "xlsx"])

if uploaded_file is not None:
    # ファイルの拡張子を確認して読み込む
    if uploaded_file.name.endswith(".csv"):
        df = pd.read_csv(uploaded_file)
    else:
        df = pd.read_excel(uploaded_file)

    # データの基本情報を表示
    st.subheader("データの基本情報")
    st.write(df.info())

    # データの先頭5行を表示
    st.subheader("データの先頭5行")
    st.write(df.head())

